/* Kurze Übungsbeschreibungen für die eingebauten Übungen. Eigene Texte (selbst geschrieben oder aus Wikipedia geholt) werden in der App gespeichert und haben Vorrang. */
(function () {
  'use strict';
  window.KT = window.KT || {};
  KT.info = {
    'MedBall-Rotationswurf': 'Seitlich zur Wand stehen und den Medizinball mit einer kraftvollen Rotation aus Hüfte und Rumpf gegen die Wand werfen. Explosiv und mit leichtem Ball, nach jedem Wurf neu aufbauen.',
    'Box Sprung': 'Beidbeiniger Sprung aus dem Stand auf eine Box, dabei die Arme mitschwingen. Weich landen, aufrecht stehen und kontrolliert zurücksteigen, nicht zurückspringen.',
    'Hexbar Züge': 'Explosives Hochziehen der Hexbar vom Boden bis zur Streckung von Hüfte und Knien, mit anschließendem Schulterzucken. Schnelle Kraft für Sprung und Sprint, leichtes bis mittleres Gewicht.',
    'Sprung mit Kurzhantel': 'Mit leichten Kurzhanteln in den Händen aus der Viertelbeuge senkrecht hochspringen. Hüfte, Knie und Fuß voll strecken und weich auf dem Vorfuß landen.',
    'MedBall-Brustwurf': 'Den Medizinball vor der Brust halten und mit beiden Armen und einem Schritt kraftvoll nach vorn gegen die Wand oder zum Partner stoßen. Schnell abdrücken, Rumpf stabil.',
    'Kniebeuge vorn': 'Die Langhantel liegt vorn auf den Schultern, die Ellbogen zeigen nach vorn. Hüfte und Knie gleichzeitig beugen, Rumpf aufrecht halten und aus der Mitte des Fußes aufstehen.',
    'Kniebeuge hinten': 'Die Langhantel liegt auf dem oberen Rücken. Hüfte nach hinten schieben und gleichzeitig die Knie beugen, Rumpf gespannt, Knie folgen den Zehen, dann kraftvoll aufstehen.',
    'Ausfallschritt': 'Mit einem großen Schritt nach vorn das hintere Knie Richtung Boden senken und mit dem vorderen Bein wieder abdrücken. Rumpf aufrecht, vorderes Knie über dem Fuß.',
    'Split Squat': 'Im Ausfallschritt-Stand mit festem Fußabstand bleiben und nur auf und ab beugen. Das hintere Knie fast zum Boden, das Gewicht liegt hauptsächlich auf dem vorderen Bein.',
    'Beinpresse': 'Im Sitzen oder Liegen die Plattform mit beiden Beinen wegdrücken und kontrolliert zurückführen. Rücken fest an der Lehne, Knie nicht ganz durchstrecken, Fersen bleiben am Brett.',
    'Beinstrecker': 'Im Sitzen die Beine gegen den Widerstand strecken, oben kurz halten und langsam senken. Isoliert die Oberschenkelvorderseite, Gewicht so wählen, dass die Hüfte nicht abhebt.',
    'Bankdrücken': 'Auf der Bank liegen, Schulterblätter zusammen und nach unten, Füße fest am Boden. Die Stange kontrolliert zur unteren Brust senken und kraftvoll nach oben drücken.',
    'Schrägbankdrücken': 'Wie Bankdrücken auf einer leicht geneigten Bank (etwa 30 Grad). Betont die obere Brust und die vorderen Schultern, die Stange wird zur oberen Brust geführt.',
    'Überkopfdrücken': 'Im Stand die Stange von den Schultern senkrecht über den Kopf drücken. Gesäß und Bauch fest, Kopf kurz zurück, oben die Arme strecken und die Stange über den Schultern halten.',
    'Kurzhantel-Schulterdrücken': 'Mit je einer Kurzhantel auf Schulterhöhe beide Arme senkrecht nach oben drücken und kontrolliert absenken. Im Sitzen oder Stehen, Rumpf stabil, kein Hohlkreuz.',
    'Bankdrücken mit Bändern': 'Bankdrücken mit Widerstandsbändern, die den Widerstand zum Ende der Bewegung erhöhen. Das Band wird an Stange und Bank oder Rack befestigt, Bewegung wie beim normalen Bankdrücken.',
    'Brustpresse': 'An der Maschine die Griffe aus Brusthöhe nach vorn wegdrücken und langsam zurückführen. Schulterblätter an der Lehne, Handgelenke gerade, kontrollierte Bewegung.',
    'Hexbar Kreuzheben': 'In der sechseckigen Stange stehen, Hüfte beugen, Rücken gerade, die Griffe fassen und durch Strecken von Hüfte und Knien aufrichten. Die Stange bleibt nah am Körper.',
    'Rumänisches Kreuzheben': 'Mit leicht gebeugten Knien die Hüfte nach hinten schieben und die Stange an den Beinen entlang bis unter die Knie senken, dann durch Hüftstreckung aufrichten. Rücken bleibt gerade.',
    'Hip Thrust': 'Mit dem oberen Rücken an eine Bank gelehnt, die Stange auf der Hüfte, die Hüfte durch Anspannen des Gesäßes nach oben drücken. Oben kurz halten, Kinn zur Brust, Rippen unten.',
    'Beinbeuger': 'Im Liegen oder Sitzen den Unterschenkel gegen den Widerstand zum Gesäß beugen und langsam zurücklassen. Isoliert die Oberschenkelrückseite, Hüfte bleibt unten.',
    'Kettlebell Swing': 'Die Kettlebell mit beiden Händen zwischen den Beinen schwingen und durch eine explosive Hüftstreckung bis auf Brusthöhe bringen. Der Impuls kommt aus der Hüfte, nicht aus den Armen.',
    'Einbeiniges Kreuzheben': 'Auf einem Bein stehen, Oberkörper nach vorn neigen, während das freie Bein nach hinten wandert, und die Gewichte an dem Standbein entlang senken. Hüfte bleibt gerade, Rücken neutral.',
    'Latzug': 'Im Sitzen die Stange von oben mit breitem Griff zur oberen Brust ziehen, Ellbogen nach unten und hinten, Brust raus. Kontrolliert zurückführen, nicht mit dem Körper schwingen.',
    'Klimmzug': 'Im Hang am Reck mit gestreckten Armen starten und den Körper hochziehen, bis das Kinn über der Stange ist. Schulterblätter zuerst nach unten ziehen, kontrolliert wieder ablassen.',
    'Kurzhantel Rudern': 'Mit einer Hand und einem Knie auf der Bank abgestützt die Kurzhantel mit geradem Rücken zur Hüfte ziehen, Ellbogen nah am Körper. Oben die Schulterblätter zusammenziehen.',
    'Ruderzug eng': 'Am Seilzug sitzend den engen Griff zum Bauch ziehen, Brust raus, Schulterblätter zusammen. Ellbogen am Körper entlang, kontrolliert zurückführen ohne Rundrücken.',
    'Ruderzug breit': 'Am Seilzug sitzend den breiten Griff Richtung Brust ziehen, Ellbogen weit nach außen und hinten. Betont den oberen Rücken und die hinteren Schultern.',
    'Band Rudern': 'Ein Widerstandsband an einem festen Punkt befestigen und im Sitzen oder Stehen zum Körper rudern. Schulterblätter am Ende zusammenziehen, Spannung im Band halten.',
    'Ruderergometer': 'Cardio-Gerät: Beine, Rumpf und Arme in dieser Reihenfolge strecken und in umgekehrter Reihenfolge zurückkehren. Eingetragen werden Zeit, Strecke, Drag-Faktor und Belastungsempfinden.',
    'Skiergometer': 'Cardio-Gerät: beide Griffe aus dem Stand von oben nach unten ziehen, dabei Hüfte und Knie beugen. Ganzkörperbelastung mit Zeit, Strecke, Drag-Faktor und Belastungsempfinden.',
    'Fahrradergometer': 'Cardio-Gerät: gleichmäßiges Treten im gewählten Widerstand, Sattel auf Hüfthöhe. Eingetragen werden Zeit, Strecke oder Leistung und das Belastungsempfinden.',
    'Airbike': 'Cardio-Gerät mit Luftwiderstand: Beine treten und Arme ziehen und drücken gleichzeitig, je härter, desto mehr Widerstand. Eingetragen werden Zeit, Kalorien und Belastungsempfinden.',
    'Ellipsenmaschine': 'Cardio-Gerät (Crosstrainer): gleitende Schrittbewegung mit mitbewegten Armen, gelenkschonend. Eingetragen werden Zeit, Kalorien und Belastungsempfinden.',
    'Allgemeine Erwärmung': 'Lockeres Gehen oder leichtes Mobilisieren der großen Gelenke mit dem Körpergewicht, bis dir warm ist. Dient der Vorbereitung auf die Hauptübungen.',
    'Seitstütz statisch': 'Seitlich auf einem Unterarm und den Füßen aufstützen, Körper bildet eine gerade Linie, Hüfte oben halten. Auf jeder Seite die vorgegebene Zeit halten.',
    'Kabel-Seitneigen': 'Seitlich zum Kabelzug stehen und den Oberkörper gegen den Widerstand zur Seite neigen und wieder aufrichten. Trainiert die seitliche Rumpfmuskulatur, Hüfte bleibt ruhig.',
    'Suitcase Carry': 'Ein schweres Gewicht in einer Hand wie einen Koffer tragen und dabei aufrecht und gerade bleiben, ohne zur Seite zu kippen. Trainiert die seitliche Rumpfstabilität.',
    'Roll-Out': 'Aus dem Kniestand ein Rollrad oder eine Langhantel mit gestreckten Armen nach vorn rollen und mit Bauchspannung zurückziehen. Rücken gerade halten, kein Hohlkreuz.',
    'Plank': 'Auf Unterarmen und Fußspitzen aufstützen, Körper in einer geraden Linie halten, Bauch und Gesäß fest. Atmen, Hüfte weder hängen lassen noch hochschieben.',
    'Hollow-Hold': 'In Rückenlage Beine und Schultern leicht anheben, Lendenwirbelsäule am Boden halten und die Position halten. Arme gestreckt über dem Kopf, Körper bildet eine flache Schale.',
    'Pallof Press': 'Seitlich zum Kabelzug oder Band stehen, den Griff vor die Brust nehmen und gerade nach vorn drücken, ohne dass der Körper aufdreht. Trainiert die Rotationsstabilität.',
    'Kabelrotation': 'Seitlich zum Kabelzug stehen und den Griff mit gestreckten Armen aus der Rumpfrotation diagonal ziehen. Die Bewegung kommt aus Rumpf und Hüfte, Füße bleiben fest.',
    'Face Pull': 'Das Seil auf Gesichtshöhe zum Gesicht ziehen und die Hände auseinander und nach außen führen. Ellbogen hoch, Schulterblätter zusammen, stärkt die hintere Schulter.',
    'Wadenheben': 'Im Stand die Fersen anheben, oben kurz halten und langsam wieder absenken. Fuß voll durchstrecken, am Ende die Ferse unter die Stufenkante sinken lassen.',
    'Hammer Curl': 'Mit einer Kurzhantel in jeder Hand und neutralen Handgelenken (Daumen oben) die Ellbogen beugen, ohne die Oberarme zu bewegen. Kontrolliert wieder senken.',
    'Wadenheben einbeinig exzentrisch': 'Auf einer Stufe mit beiden Beinen hochgehen und nur mit einem Bein langsam (drei bis vier Sekunden) absenken. Prehab für die Achillessehne, Gewicht in kleinen Schritten steigern.',
    'Wadenheben einbeinig exzentrisch, Knie gebeugt': 'Wie das exzentrische Wadenheben, aber mit leicht gebeugtem Knie, so wird besonders der tiefe Wadenmuskel und die Achillessehne belastet. Langsam absenken.',
    'Wadenheben exzentrisch an der Maschine': 'An der Wadenmaschine mit beiden Beinen hochdrücken und nur mit einem Bein langsam absenken. Gleichmäßiges Tempo, Ferse tief, ohne zu federn.',
    'Wadenheben zwei Beine hoch, ein Bein runter': 'Mit beiden Beinen anheben, dann ein Bein lösen und nur mit dem anderen langsam absenken. Dann Seite wechseln. Eine gute Einstiegsvariante für die exzentrische Belastung.',
    'Wadenhalten isometrisch': 'Auf den Zehenspitzen oben anhalten und die Position die vorgegebene Zeit halten, ohne zu wackeln. Isometrische Belastung bei Beschwerden der Achillessehne.',
    'Schulterflexion an der Wand': 'Mit dem Rücken zur Wand stehen und die gestreckten Arme seitlich an der Wand nach oben über den Kopf führen. Rippen unten, Lendenwirbelsäule an der Wand, Vorbereitung für den Handstand.',
    'Scapular Wall Slide': 'Unterarme an die Wand legen und mit der Schulterblattbewegung die Arme an der Wand nach oben gleiten lassen. Schulterblätter bewegen sich mit, Schultern bleiben tief.',
    'Scapular Shrug im Stütz': 'Im Liegestütz mit gestreckten Armen nur mit den Schulterblättern zwischen Heben und Senken wechseln. Arme bleiben gestreckt, trainiert die Schulterstabilität für den Handstand.',
    'Hollow-Body-Halten': 'In Rückenlage mit angehobenen Armen, Schultern und Beinen die flache Schalenform halten, Lendenwirbelsäule am Boden. Körperspannung für den Handstand.',
    'Brust-zur-Wand-Handstand halten': 'Mit dem Bauch zur Wand an der Wand hochgehen, Körper möglichst gerade, Schultern aktiv hochdrücken und halten. Kraft und Körperspannung im Handstand.',
    'Handgelenk-Vorbereitung': 'Handgelenke vor dem Handstand mobilisieren: kreisen, im Vierfüßlerstand sanft nach vorn und zur Seite belasten. Vorbereitung auf das Gewicht auf den Händen.',
    'Serratus Wall Slide': 'Unterarme an der Wand, die Arme nach oben gleiten und dabei den Schultergürtel aktiv nach vorn oben drücken. Kräftigt den vorderen Sägemuskel (Serratus).',
    'Band-Außenrotation': 'Ellbogen an den Körper, Band halten und den Unterarm gegen den Widerstand nach außen drehen. Kräftigt die Rotatorenmanschette, Oberarm bleibt am Körper.',
    'Scapula Push-up': 'Im Stütz mit gestreckten Armen die Schulterblätter zusammen- und wieder auseinanderziehen, ohne die Ellbogen zu beugen. Aktiviert den vorderen Sägemuskel.',
    'Face Pull mit Außenrotation': 'Wie Face Pull, am Ende zusätzlich die Hände nach oben außen drehen, bis die Unterarme senkrecht stehen. Stärkt die hintere Schulter und die Rotatoren.',
    'Y-T-W-Heben': 'In Bauchlage oder vorgebeugt die Arme nacheinander in Y-, T- und W-Form anheben. Kräftigt die Schulterblattmuskulatur, Daumen nach oben, ohne Schwung.',
    'Wall Angels': 'Mit dem Rücken an der Wand die Arme in der Schulterhöhe an der Wand nach oben und unten gleiten lassen. Kopf, Rücken und Hände bleiben an der Wand.',
    'Band Pull-Apart': 'Ein Band mit gestreckten Armen vor der Brust halten und es durch Auseinanderziehen der Arme bis zur Brust spannen. Schulterblätter zusammen, Schultern tief.',
    'Schulterblatt-Liegestütz': 'Liegestütz, bei dem nur die Schulterblätter bewegt werden: oben zusammenziehen, unten auseinanderziehen, Arme bleiben gestreckt. Schulterstabilität für Druck- und Zugbewegungen.',
    'Dead Bug': 'In Rückenlage Arme und Beine nach oben, dann gegengleich Arm und Bein absenken, ohne dass sich das Hohlkreuz bildet. Bauchspannung halten, ruhig atmen.',
    'Bird Dog': 'Im Vierfüßlerstand gegengleich Arm und Bein waagerecht strecken und kurz halten. Rücken und Hüfte bleiben ruhig, trainiert Rumpfstabilität und Haltung.',
    'Glute Bridge': 'In Rückenlage die Fersen aufstellen und die Hüfte durch Anspannen des Gesäßes anheben, bis Schultern, Hüfte und Knie eine Linie bilden. Oben kurz halten.',
    'Clamshell mit Band': 'In Seitenlage mit gebeugten Knien und einem Band über den Knien das obere Knie wie eine Muschel öffnen. Hüfte bleibt stabil, kräftigt die seitliche Gesäßmuskulatur.',
    'Hüftbeuger-Dehnung': 'Im Ausfallschritt mit dem hinteren Knie am Boden die Hüfte nach vorn schieben, bis die Vorderseite der hinteren Hüfte spürbar gedehnt wird. Oberkörper aufrecht.',
    'Katze-Kuh': 'Im Vierfüßlerstand den Rücken abwechselnd rund machen (Katze) und durchhängen lassen (Kuh), im Rhythmus der Atmung. Mobilisiert die gesamte Wirbelsäule.',
    'Thorakale Rotation (Seitenlage)': 'In Seitenlage die Knie anwinkeln und den oberen Arm weit nach hinten öffnen, Blick folgt der Hand. Mobilisiert die Brustwirbelsäule, Knie bleiben zusammen.',
    'Türrahmen-Dehnung Brust': 'Unterarme links und rechts am Türrahmen, einen Schritt nach vorn gehen, bis die Brust gedehnt wird. Rücken gerade, die Dehnung ruhig halten.',
    'Brustwirbelsäule über Rolle': 'Mit dem oberen Rücken auf eine Faszienrolle legen, Hände hinter dem Kopf, und sich vorsichtig über die Rolle nach hinten strecken. Mobilisiert die Brustwirbelsäule.',
    'Farmer Carry': 'Mit je einem schweren Gewicht in beiden Händen aufrecht und gerade eine Strecke gehen. Schultern tief, Rumpf fest, trainiert Griffkraft und Rumpfstabilität.'
  };
})();
